# Generated by Django 5.2.3 on 2025-06-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_color_item_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_code',
            field=models.CharField(default='#FFFFFF', max_length=8),
        ),
    ]
